version: 0.2

phases:
  install:
    commands:
      - sudo apt-get update -y
      - sudo apt-get update
      - sudo apt-get install clang cmake3 cppcheck -y 
  pre_build:
    commands:
      - export CC=clang
      - export CXX=clang++
  build:
    commands:
      - echo Build started on `date`
      - ./cppcheck.sh
      - mkdir build
      - cd build
      - cmake ../ 
      - make
      - make test
  post_build:
    commands:
      - echo Build completed on `date`

