version: 0.2

phases:
  install:
    commands:
      - sudo apt-get install software-properties-common
      - sudo add-apt-repository ppa:george-edison55/cmake-3.x
      - sudo add-apt-repository ppa:george-edison55/cmake-3.x
      - sudo apt-get update -y
      - sudo apt-get update
      - sudo apt-get install gcc g++ cmake cppcheck -y 
  pre_build:
    commands:
      - export CC=gcc
      - export CXX=g++
  build:
    commands:
      - echo Build started on `date`
      - ./cppcheck.sh
      - mkdir build
      - cd build
      - cmake ../ 
      - make
      - make test
  post_build:
    commands:
      - echo Build completed on `date`

